# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editProfile.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_editProfile(object):
    def setupUi(self, editProfile):
        editProfile.setObjectName("editProfile")
        editProfile.resize(792, 467)
        editProfile.setStyleSheet("")
        self.exitButton = QtWidgets.QPushButton(editProfile)
        self.exitButton.setGeometry(QtCore.QRect(670, 420, 80, 28))
        self.exitButton.setStyleSheet("")
        self.exitButton.setObjectName("exitButton")
        self.saveButton = QtWidgets.QPushButton(editProfile)
        self.saveButton.setGeometry(QtCore.QRect(560, 420, 80, 28))
        self.saveButton.setStyleSheet("")
        self.saveButton.setObjectName("saveButton")
        self.frame = QtWidgets.QFrame(editProfile)
        self.frame.setGeometry(QtCore.QRect(20, 60, 751, 341))
        self.frame.setStyleSheet("background:white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(30, 70, 221, 201))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("image: url(:/doctor_icon.png);\n"
"border-style:solid;\n"
"border-width:1px;\n"
"border-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.doctorIDLabel = QtWidgets.QLabel(self.frame)
        self.doctorIDLabel.setGeometry(QtCore.QRect(30, 10, 101, 41))
        self.doctorIDLabel.setObjectName("doctorIDLabel")
        self.doctorID = QtWidgets.QLabel(self.frame)
        self.doctorID.setGeometry(QtCore.QRect(140, 10, 211, 41))
        self.doctorID.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;")
        self.doctorID.setObjectName("doctorID")
        self.uploadImage = QtWidgets.QPushButton(self.frame)
        self.uploadImage.setGeometry(QtCore.QRect(80, 290, 111, 28))
        self.uploadImage.setObjectName("uploadImage")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(270, 20, 451, 301))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.personal = QtWidgets.QWidget()
        self.personal.setObjectName("personal")
        self.address = QtWidgets.QTextBrowser(self.personal)
        self.address.setGeometry(QtCore.QRect(140, 20, 291, 101))
        self.address.setStyleSheet("")
        self.address.setObjectName("address")
        self.addressLabel = QtWidgets.QLabel(self.personal)
        self.addressLabel.setGeometry(QtCore.QRect(30, 60, 111, 31))
        self.addressLabel.setObjectName("addressLabel")
        self.city = QtWidgets.QLabel(self.personal)
        self.city.setGeometry(QtCore.QRect(140, 150, 181, 31))
        self.city.setStyleSheet("font-size:12pt;")
        self.city.setObjectName("city")
        self.stateLabel = QtWidgets.QLabel(self.personal)
        self.stateLabel.setGeometry(QtCore.QRect(30, 200, 111, 31))
        self.stateLabel.setObjectName("stateLabel")
        self.state = QtWidgets.QLabel(self.personal)
        self.state.setGeometry(QtCore.QRect(140, 200, 181, 31))
        self.state.setStyleSheet("font-size:12pt;")
        self.state.setObjectName("state")
        self.cityLabel = QtWidgets.QLabel(self.personal)
        self.cityLabel.setGeometry(QtCore.QRect(30, 150, 111, 31))
        self.cityLabel.setObjectName("cityLabel")
        self.tabWidget.addTab(self.personal, "")
        self.professional = QtWidgets.QWidget()
        self.professional.setObjectName("professional")
        self.hospital = QtWidgets.QLabel(self.professional)
        self.hospital.setGeometry(QtCore.QRect(205, 190, 201, 31))
        self.hospital.setStyleSheet("font-size:12pt;")
        self.hospital.setObjectName("hospital")
        self.specializationLabel = QtWidgets.QLabel(self.professional)
        self.specializationLabel.setGeometry(QtCore.QRect(30, 110, 171, 31))
        self.specializationLabel.setObjectName("specializationLabel")
        self.qualificationLabel = QtWidgets.QLabel(self.professional)
        self.qualificationLabel.setGeometry(QtCore.QRect(30, 30, 171, 31))
        self.qualificationLabel.setObjectName("qualificationLabel")
        self.hospitalLabel = QtWidgets.QLabel(self.professional)
        self.hospitalLabel.setGeometry(QtCore.QRect(30, 190, 111, 31))
        self.hospitalLabel.setObjectName("hospitalLabel")
        self.qualificationComboBox = QtWidgets.QComboBox(self.professional)
        self.qualificationComboBox.setGeometry(QtCore.QRect(200, 30, 171, 27))
        self.qualificationComboBox.setObjectName("qualificationComboBox")
        self.specializationComboBox = QtWidgets.QComboBox(self.professional)
        self.specializationComboBox.setGeometry(QtCore.QRect(200, 110, 171, 27))
        self.specializationComboBox.setObjectName("specializationComboBox")
        self.tabWidget.addTab(self.professional, "")
        self.name = QtWidgets.QLabel(editProfile)
        self.name.setGeometry(QtCore.QRect(40, 10, 371, 41))
        self.name.setStyleSheet("font-weight:bold;\n"
"font-size:13pt;")
        self.name.setObjectName("name")

        self.retranslateUi(editProfile)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(editProfile)

    def retranslateUi(self, editProfile):
        _translate = QtCore.QCoreApplication.translate
        editProfile.setWindowTitle(_translate("editProfile", "Profile"))
        self.exitButton.setText(_translate("editProfile", "EXIT"))
        self.saveButton.setText(_translate("editProfile", "SAVE"))
        self.doctorIDLabel.setText(_translate("editProfile", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Doctor ID :</span></p></body></html>"))
        self.doctorID.setText(_translate("editProfile", "Doctor ID"))
        self.uploadImage.setText(_translate("editProfile", "Upload Image"))
        self.address.setPlaceholderText(_translate("editProfile", "Update your address"))
        self.addressLabel.setText(_translate("editProfile", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Address :</span></p></body></html>"))
        self.city.setText(_translate("editProfile", "city_name"))
        self.stateLabel.setText(_translate("editProfile", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">State : </span></p></body></html>"))
        self.state.setText(_translate("editProfile", "state_name"))
        self.cityLabel.setText(_translate("editProfile", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">City : </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.personal), _translate("editProfile", "Personal"))
        self.hospital.setText(_translate("editProfile", "hospital_name"))
        self.specializationLabel.setText(_translate("editProfile", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Specialization :</span></p></body></html>"))
        self.qualificationLabel.setText(_translate("editProfile", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Qualification :</span></p></body></html>"))
        self.hospitalLabel.setText(_translate("editProfile", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Hospital : </span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.professional), _translate("editProfile", "Professional"))
        self.name.setText(_translate("editProfile", "first_name last_name"))

import img_rc
