from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from Dialogs.changePassword import *
from Dialogs.Notice.NoticeList import *
from Dialogs.Message.MessageDialog import *
from Dialogs.superadmin.TestCenters.new_testCenterProfile import *
from Dialogs.events import *

class testCenterHome(object):
    def setup(self, testCenterHome,loginData= None):
        self.logindata = loginData
        import requests
        URL = "http://127.0.0.1:8000/api/testcentre/"
        data = {
            "username" : self.logindata["id"]
        }
        r = requests.get(url=URL,params=data)
        l = r.json()
        self.testcenterdata = l[0]
        testCenterHome.setObjectName("testCenterHome")
        testCenterHome.resize(1366, 768)
        self.centralwidget = QtWidgets.QWidget(testCenterHome)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(550, 20, 281, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(QtCore.QSize(0, 50))
        self.title.setMaximumSize(QtCore.QSize(400, 70))
        self.title.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.title.setObjectName("title")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(1300, 20, 50, 50))
        self.logout.setMinimumSize(QtCore.QSize(50, 50))
        self.logout.setMaximumSize(QtCore.QSize(50, 50))
        self.logout.setStyleSheet("border:none;")
        self.logout.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../MDTouch/Images/LogoutIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout.setIcon(icon)
        self.logout.setIconSize(QtCore.QSize(50, 50))
        self.logout.setObjectName("logout")
        self.inbox = QtWidgets.QPushButton(self.centralwidget)
        self.inbox.setGeometry(QtCore.QRect(1230, 20, 50, 50))
        self.inbox.setMinimumSize(QtCore.QSize(50, 50))
        self.inbox.setMaximumSize(QtCore.QSize(50, 50))
        self.inbox.setStyleSheet("border:none;")
        self.inbox.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../MDTouch/Images/inbox_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inbox.setIcon(icon1)
        self.inbox.setIconSize(QtCore.QSize(50, 50))
        self.inbox.setObjectName("inbox")
        self.testCenterName = QtWidgets.QLabel(self.centralwidget)
        self.testCenterName.setGeometry(QtCore.QRect(110, 30, 400, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testCenterName.sizePolicy().hasHeightForWidth())
        self.testCenterName.setSizePolicy(sizePolicy)
        self.testCenterName.setMinimumSize(QtCore.QSize(100, 30))
        self.testCenterName.setMaximumSize(QtCore.QSize(400, 100))
        self.testCenterName.setStyleSheet("font-size:15pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.testCenterName.setObjectName("testCenterName")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 160, 1291, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.testRequests = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.testRequests.setMinimumSize(QtCore.QSize(100, 100))
        self.testRequests.setMaximumSize(QtCore.QSize(100, 100))
        self.testRequests.setStyleSheet("border:none;")
        self.testRequests.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../MDTouch/Images/test_requests.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.testRequests.setIcon(icon2)
        self.testRequests.setIconSize(QtCore.QSize(100, 100))
        self.testRequests.setObjectName("testRequests")
        self.horizontalLayout.addWidget(self.testRequests)
        self.testRecords = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.testRecords.setMinimumSize(QtCore.QSize(100, 100))
        self.testRecords.setMaximumSize(QtCore.QSize(100, 100))
        self.testRecords.setStyleSheet("border:none;")
        self.testRecords.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../MDTouch/Images/medical_records.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.testRecords.setIcon(icon3)
        self.testRecords.setIconSize(QtCore.QSize(100, 100))
        self.testRecords.setObjectName("testRecords")
        self.horizontalLayout.addWidget(self.testRecords)
        self.createBill = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.createBill.setMinimumSize(QtCore.QSize(100, 100))
        self.createBill.setMaximumSize(QtCore.QSize(100, 100))
        self.createBill.setStyleSheet("border:none;")
        self.createBill.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../MDTouch/Images/write_bill.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createBill.setIcon(icon4)
        self.createBill.setIconSize(QtCore.QSize(100, 100))
        self.createBill.setObjectName("createBill")
        self.horizontalLayout.addWidget(self.createBill)
        self.addTest = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addTest.setMinimumSize(QtCore.QSize(100, 100))
        self.addTest.setMaximumSize(QtCore.QSize(100, 100))
        self.addTest.setStyleSheet("border:none;")
        self.addTest.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../MDTouch/Images/add_test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addTest.setIcon(icon5)
        self.addTest.setIconSize(QtCore.QSize(100, 100))
        self.addTest.setObjectName("addTest")
        self.horizontalLayout.addWidget(self.addTest)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 440, 1291, 121))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.events = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.events.setMinimumSize(QtCore.QSize(100, 100))
        self.events.setMaximumSize(QtCore.QSize(100, 100))
        self.events.setStyleSheet("border:none;")
        self.events.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../MDTouch/Images/event.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.events.setIcon(icon6)
        self.events.setIconSize(QtCore.QSize(100, 100))
        self.events.setObjectName("events")
        self.horizontalLayout_2.addWidget(self.events)
        self.notices = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.notices.setMinimumSize(QtCore.QSize(100, 100))
        self.notices.setMaximumSize(QtCore.QSize(100, 100))
        self.notices.setStyleSheet("border:none;")
        self.notices.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../MDTouch/Images/notices.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notices.setIcon(icon7)
        self.notices.setIconSize(QtCore.QSize(100, 100))
        self.notices.setObjectName("notices")
        self.horizontalLayout_2.addWidget(self.notices)
        self.profile = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.profile.setMinimumSize(QtCore.QSize(100, 100))
        self.profile.setMaximumSize(QtCore.QSize(100, 100))
        self.profile.setStyleSheet("border:none;")
        self.profile.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../MDTouch/Images/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile.setIcon(icon8)
        self.profile.setIconSize(QtCore.QSize(100, 100))
        self.profile.setObjectName("profile")
        self.horizontalLayout_2.addWidget(self.profile)
        self.changePassword = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.changePassword.setMinimumSize(QtCore.QSize(100, 100))
        self.changePassword.setMaximumSize(QtCore.QSize(100, 100))
        self.changePassword.setStyleSheet("border:none;")
        self.changePassword.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../MDTouch/Images/change_password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.changePassword.setIcon(icon9)
        self.changePassword.setIconSize(QtCore.QSize(100, 100))
        self.changePassword.setObjectName("changePassword")
        self.horizontalLayout_2.addWidget(self.changePassword)
        self.testRecordsLabel = QtWidgets.QLabel(self.centralwidget)
        self.testRecordsLabel.setGeometry(QtCore.QRect(415, 290, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testRecordsLabel.sizePolicy().hasHeightForWidth())
        self.testRecordsLabel.setSizePolicy(sizePolicy)
        self.testRecordsLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.testRecordsLabel.setMaximumSize(QtCore.QSize(400, 100))
        self.testRecordsLabel.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.testRecordsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testRecordsLabel.setObjectName("testRecordsLabel")
        self.testRequestsLabel = QtWidgets.QLabel(self.centralwidget)
        self.testRequestsLabel.setGeometry(QtCore.QRect(160, 290, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testRequestsLabel.sizePolicy().hasHeightForWidth())
        self.testRequestsLabel.setSizePolicy(sizePolicy)
        self.testRequestsLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.testRequestsLabel.setMaximumSize(QtCore.QSize(400, 100))
        self.testRequestsLabel.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.testRequestsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.testRequestsLabel.setObjectName("testRequestsLabel")
        self.createBillLabel = QtWidgets.QLabel(self.centralwidget)
        self.createBillLabel.setGeometry(QtCore.QRect(700, 290, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createBillLabel.sizePolicy().hasHeightForWidth())
        self.createBillLabel.setSizePolicy(sizePolicy)
        self.createBillLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.createBillLabel.setMaximumSize(QtCore.QSize(400, 100))
        self.createBillLabel.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.createBillLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.createBillLabel.setObjectName("createBillLabel")
        self.noticesLabel = QtWidgets.QLabel(self.centralwidget)
        self.noticesLabel.setGeometry(QtCore.QRect(420, 550, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noticesLabel.sizePolicy().hasHeightForWidth())
        self.noticesLabel.setSizePolicy(sizePolicy)
        self.noticesLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.noticesLabel.setMaximumSize(QtCore.QSize(400, 100))
        self.noticesLabel.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.noticesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.noticesLabel.setObjectName("noticesLabel")
        self.profileLabel = QtWidgets.QLabel(self.centralwidget)
        self.profileLabel.setGeometry(QtCore.QRect(705, 550, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileLabel.sizePolicy().hasHeightForWidth())
        self.profileLabel.setSizePolicy(sizePolicy)
        self.profileLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.profileLabel.setMaximumSize(QtCore.QSize(400, 100))
        self.profileLabel.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.profileLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.profileLabel.setObjectName("profileLabel")
        self.changePasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.changePasswordLabel.setGeometry(QtCore.QRect(990, 555, 221, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.changePasswordLabel.sizePolicy().hasHeightForWidth())
        self.changePasswordLabel.setSizePolicy(sizePolicy)
        self.changePasswordLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.changePasswordLabel.setMaximumSize(QtCore.QSize(400, 100))
        self.changePasswordLabel.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.changePasswordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.changePasswordLabel.setObjectName("changePasswordLabel")
        self.addTestLabel = QtWidgets.QLabel(self.centralwidget)
        self.addTestLabel.setGeometry(QtCore.QRect(990, 290, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addTestLabel.sizePolicy().hasHeightForWidth())
        self.addTestLabel.setSizePolicy(sizePolicy)
        self.addTestLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.addTestLabel.setMaximumSize(QtCore.QSize(400, 100))
        self.addTestLabel.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.addTestLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addTestLabel.setObjectName("addTestLabel")
        self.eventsLabel = QtWidgets.QLabel(self.centralwidget)
        self.eventsLabel.setGeometry(QtCore.QRect(150, 560, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventsLabel.sizePolicy().hasHeightForWidth())
        self.eventsLabel.setSizePolicy(sizePolicy)
        self.eventsLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.eventsLabel.setMaximumSize(QtCore.QSize(400, 100))
        self.eventsLabel.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;\n"
"text-decoration: underline")
        self.eventsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.eventsLabel.setObjectName("eventsLabel")
        testCenterHome.setCentralWidget(self.centralwidget)

        self.retranslateUi(testCenterHome)
        QtCore.QMetaObject.connectSlotsByName(testCenterHome)

    def retranslateUi(self, testCenterHome):
        _translate = QtCore.QCoreApplication.translate
        testCenterHome.setWindowTitle(_translate("testCenterHome", "MainWindow"))
        self.title.setText(_translate("testCenterHome", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25pt; font-weight:600; text-decoration: underline;\">MDTouch</span></p></body></html>"))
        self.testCenterName.setText(_translate("testCenterHome", "test_center_name"))
        self.testRecordsLabel.setText(_translate("testCenterHome", "<html><head/><body><p><span style=\" font-size:12pt;\">Records</span></p></body></html>"))
        self.testRequestsLabel.setText(_translate("testCenterHome", "<html><head/><body><p><span style=\" font-size:12pt;\">Requests</span></p></body></html>"))
        self.createBillLabel.setText(_translate("testCenterHome", "<html><head/><body><p><span style=\" font-size:12pt;\">Create Bill</span></p></body></html>"))
        self.noticesLabel.setText(_translate("testCenterHome", "<html><head/><body><p><span style=\" font-size:12pt;\">Notices</span></p></body></html>"))
        self.profileLabel.setText(_translate("testCenterHome", "<html><head/><body><p><span style=\" font-size:12pt;\">Profile</span></p></body></html>"))
        self.changePasswordLabel.setText(_translate("testCenterHome", "<html><head/><body><p><span style=\" font-size:12pt;\">Change<br>Password</span></p></body></html>"))
        self.addTestLabel.setText(_translate("testCenterHome", "<html><head/><body><p><span style=\" font-size:12pt;\">Add Test</span></p></body></html>"))
        self.eventsLabel.setText(_translate("testCenterHome", "<html><head/><body><p><span style=\" font-size:12pt;\">Events</span></p></body></html>"))
        self.clickEvents(testCenterHome)
        self.testCenterName.setText(self.testcenterdata["name"])

    def clickEvents(self, parent):
        self.logout.clicked.connect(lambda : self.clickOnLogoutButton(parent))
        self.changePassword.clicked.connect(lambda : self.clickOnChangePassword(parent))
        self.notices.clicked.connect(lambda : self.clickOnNotice())
        self.inbox.clicked.connect(lambda : self.clickOnMessages(parent))
        self.events.clicked.connect(lambda : self.clickOnEvents())
        self.profile.clicked.connect(lambda : self.clickOnProfile(parent))


    def clickOnLogoutButton(self,parent):
        parent.loginpage.setup(parent)

    def clickOnChangePassword(self,parent):
        self.window = QDialog()
        self.dialog = changePassword()
        self.dialog.setup(self.window,self.logindata,self)
        self.window.setModal(True)
        self.window.show()

    def clickOnNotice(self):
        self.window = QDialog()
        self.dialog = noticeList()
        self.dialog.setup(self.window)
        self.window.setModal(True)
        self.window.show()
    def clickOnMessages(self,parent):
        self.window = QDialog()
        self.dialog = messageDialog()
        self.dialog.setup(self.window, self.logindata)
        self.window.setModal(True)
        self.window.show()

    def clickOnProfile(self,parent):
        self.window = QDialog()
        self.dialog = new_testCenterProfile()
        self.dialog.setup(self.window,self.testcenterdata)
        self.window.setModal(True)
        self.window.show()

    def clickOnEvents(self):
        self.window = QDialog()
        self.dialog = eventsDialog()
        self.dialog.setup(self.window,'TC',self.testcenterdata)
        self.window.setModal(True)
        self.window.show()
