# Generated by Django 2.0.9 on 2019-01-04 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0024_auto_20190105_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 463636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bedbilling',
            name='checkindate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 464697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bedbilling',
            name='checkoutdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 464697, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 462640, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='diseasecured',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 468623, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='diseasesearch',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 469620, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Specialization'),
        ),
        migrations.AlterField(
            model_name='hospitalbilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 466627, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintainencebed',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 465630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintainencebed',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 465630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 461641, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateofbirth',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 47, 42, 431723, tzinfo=utc)),
        ),
    ]
