# Generated by Django 2.0.9 on 2019-01-04 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MDTouch', '0025_auto_20190105_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancebilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 288915, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentdate',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 259991, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dateofrequest',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 259991, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bedbilling',
            name='checkindate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 290908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bedbilling',
            name='checkoutdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 290908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bloodbilling',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 280936, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bloodwaste',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 281998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 287916, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='diseasecured',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 296892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='diseasesearch',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 298887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dispensarybilling',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 284926, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDTouch.Specialization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateofcreation',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 267004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateofevent',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 267004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hospitalbilling',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 294075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintainencebed',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 292903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maintainencebed',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 292903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expirydate',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 283131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturedate',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 283131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 261070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 286920, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateofbirth',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 253010, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 4, 19, 56, 1, 259026, tzinfo=utc)),
        ),
    ]
