# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'superadminBloodBanks.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_superadminBloodBanks(object):
    def setupUi(self, superadminBloodBanks):
        superadminBloodBanks.setObjectName("superadminBloodBanks")
        superadminBloodBanks.resize(1368, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(superadminBloodBanks.sizePolicy().hasHeightForWidth())
        superadminBloodBanks.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(superadminBloodBanks)
        self.centralwidget.setObjectName("centralwidget")
        self.addDoctorLabel = QtWidgets.QLabel(self.centralwidget)
        self.addDoctorLabel.setGeometry(QtCore.QRect(240, 370, 171, 78))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addDoctorLabel.sizePolicy().hasHeightForWidth())
        self.addDoctorLabel.setSizePolicy(sizePolicy)
        self.addDoctorLabel.setObjectName("addDoctorLabel")
        self.broadcastLabel = QtWidgets.QLabel(self.centralwidget)
        self.broadcastLabel.setGeometry(QtCore.QRect(960, 650, 161, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.broadcastLabel.sizePolicy().hasHeightForWidth())
        self.broadcastLabel.setSizePolicy(sizePolicy)
        self.broadcastLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.broadcastLabel.setObjectName("broadcastLabel")
        self.viewBloodBanksLabel = QtWidgets.QLabel(self.centralwidget)
        self.viewBloodBanksLabel.setGeometry(QtCore.QRect(600, 370, 181, 78))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewBloodBanksLabel.sizePolicy().hasHeightForWidth())
        self.viewBloodBanksLabel.setSizePolicy(sizePolicy)
        self.viewBloodBanksLabel.setObjectName("viewBloodBanksLabel")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(550, 20, 241, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(QtCore.QSize(0, 50))
        self.title.setMaximumSize(QtCore.QSize(400, 70))
        self.title.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.title.setObjectName("title")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(30, 0, 101, 100))
        self.back.setStyleSheet("border:none;")
        self.back.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../MdTouch/Images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon)
        self.back.setIconSize(QtCore.QSize(80, 80))
        self.back.setObjectName("back")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 500, 1311, 161))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fraud_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.fraud_2.setMaximumSize(QtCore.QSize(120, 120))
        self.fraud_2.setMouseTracking(True)
        self.fraud_2.setStyleSheet("border:none;")
        self.fraud_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../MdTouch/Images/fraud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fraud_2.setIcon(icon1)
        self.fraud_2.setIconSize(QtCore.QSize(100, 100))
        self.fraud_2.setCheckable(False)
        self.fraud_2.setObjectName("fraud_2")
        self.horizontalLayout_3.addWidget(self.fraud_2)
        self.analytics_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.analytics_2.setMaximumSize(QtCore.QSize(120, 120))
        self.analytics_2.setMouseTracking(True)
        self.analytics_2.setStyleSheet("border:none;")
        self.analytics_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../MdTouch/Images/statistics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analytics_2.setIcon(icon2)
        self.analytics_2.setIconSize(QtCore.QSize(100, 100))
        self.analytics_2.setCheckable(False)
        self.analytics_2.setObjectName("analytics_2")
        self.horizontalLayout_3.addWidget(self.analytics_2)
        self.broadcast_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.broadcast_2.setMaximumSize(QtCore.QSize(120, 120))
        self.broadcast_2.setStyleSheet("border:none;\n"
"")
        self.broadcast_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../MdTouch/Images/broadcast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.broadcast_2.setIcon(icon3)
        self.broadcast_2.setIconSize(QtCore.QSize(100, 100))
        self.broadcast_2.setObjectName("broadcast_2")
        self.horizontalLayout_3.addWidget(self.broadcast_2)
        self.removeBloodBankLabel = QtWidgets.QLabel(self.centralwidget)
        self.removeBloodBankLabel.setGeometry(QtCore.QRect(960, 370, 171, 78))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeBloodBankLabel.sizePolicy().hasHeightForWidth())
        self.removeBloodBankLabel.setSizePolicy(sizePolicy)
        self.removeBloodBankLabel.setObjectName("removeBloodBankLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 220, 1311, 171))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.addBloodBank = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addBloodBank.setMaximumSize(QtCore.QSize(120, 120))
        self.addBloodBank.setStyleSheet("border:none;")
        self.addBloodBank.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../MdTouch/Images/add_bloodBank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBloodBank.setIcon(icon4)
        self.addBloodBank.setIconSize(QtCore.QSize(100, 100))
        self.addBloodBank.setObjectName("addBloodBank")
        self.horizontalLayout_6.addWidget(self.addBloodBank)
        self.view_bloodBanks = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.view_bloodBanks.setMaximumSize(QtCore.QSize(120, 120))
        self.view_bloodBanks.setStyleSheet("border:none;")
        self.view_bloodBanks.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../MdTouch/Images/view_bloodBanks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_bloodBanks.setIcon(icon5)
        self.view_bloodBanks.setIconSize(QtCore.QSize(100, 100))
        self.view_bloodBanks.setObjectName("view_bloodBanks")
        self.horizontalLayout_6.addWidget(self.view_bloodBanks)
        self.removeBloodBank = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.removeBloodBank.setMaximumSize(QtCore.QSize(120, 120))
        self.removeBloodBank.setStyleSheet("border:none;")
        self.removeBloodBank.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../MdTouch/Images/remove_bloodBank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeBloodBank.setIcon(icon6)
        self.removeBloodBank.setIconSize(QtCore.QSize(100, 100))
        self.removeBloodBank.setObjectName("removeBloodBank")
        self.horizontalLayout_6.addWidget(self.removeBloodBank)
        self.analyticsLabel = QtWidgets.QLabel(self.centralwidget)
        self.analyticsLabel.setGeometry(QtCore.QRect(610, 650, 141, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyticsLabel.sizePolicy().hasHeightForWidth())
        self.analyticsLabel.setSizePolicy(sizePolicy)
        self.analyticsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.analyticsLabel.setObjectName("analyticsLabel")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(1240, 10, 101, 91))
        self.logout.setStyleSheet("border:none;")
        self.logout.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../MdTouch/Images/logout.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout.setIcon(icon7)
        self.logout.setIconSize(QtCore.QSize(80, 80))
        self.logout.setObjectName("logout")
        self.fraudLabel = QtWidgets.QLabel(self.centralwidget)
        self.fraudLabel.setGeometry(QtCore.QRect(240, 650, 161, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraudLabel.sizePolicy().hasHeightForWidth())
        self.fraudLabel.setSizePolicy(sizePolicy)
        self.fraudLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.fraudLabel.setObjectName("fraudLabel")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 100, 1371, 80))
        self.frame.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(120, 0, 1131, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.hospitals_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.hospitals_2.setMaximumSize(QtCore.QSize(80, 80))
        self.hospitals_2.setStyleSheet("border:none;")
        self.hospitals_2.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../MdTouch/Images/hospital.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hospitals_2.setIcon(icon8)
        self.hospitals_2.setIconSize(QtCore.QSize(50, 50))
        self.hospitals_2.setObjectName("hospitals_2")
        self.horizontalLayout_5.addWidget(self.hospitals_2)
        self.events_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.events_2.setMaximumSize(QtCore.QSize(80, 80))
        self.events_2.setStyleSheet("border:none;")
        self.events_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../MdTouch/Images/event.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.events_2.setIcon(icon9)
        self.events_2.setIconSize(QtCore.QSize(50, 50))
        self.events_2.setObjectName("events_2")
        self.horizontalLayout_5.addWidget(self.events_2)
        self.bloodBank_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.bloodBank_2.setMaximumSize(QtCore.QSize(80, 80))
        self.bloodBank_2.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"border:none;")
        self.bloodBank_2.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../MdTouch/Images/bloodbank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bloodBank_2.setIcon(icon10)
        self.bloodBank_2.setIconSize(QtCore.QSize(50, 50))
        self.bloodBank_2.setObjectName("bloodBank_2")
        self.horizontalLayout_5.addWidget(self.bloodBank_2)
        self.testCenters_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.testCenters_2.setMaximumSize(QtCore.QSize(80, 80))
        self.testCenters_2.setStyleSheet("border:none;")
        self.testCenters_2.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../MdTouch/Images/test_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.testCenters_2.setIcon(icon11)
        self.testCenters_2.setIconSize(QtCore.QSize(50, 50))
        self.testCenters_2.setObjectName("testCenters_2")
        self.horizontalLayout_5.addWidget(self.testCenters_2)
        self.doctors_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.doctors_2.setMaximumSize(QtCore.QSize(80, 80))
        self.doctors_2.setStyleSheet("border:none;")
        self.doctors_2.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../MdTouch/Images/doctor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.doctors_2.setIcon(icon12)
        self.doctors_2.setIconSize(QtCore.QSize(50, 50))
        self.doctors_2.setObjectName("doctors_2")
        self.horizontalLayout_5.addWidget(self.doctors_2)
        self.dispensary_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.dispensary_2.setMaximumSize(QtCore.QSize(80, 80))
        self.dispensary_2.setStyleSheet("border:none;")
        self.dispensary_2.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../MdTouch/Images/dispensary.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dispensary_2.setIcon(icon13)
        self.dispensary_2.setIconSize(QtCore.QSize(50, 50))
        self.dispensary_2.setObjectName("dispensary_2")
        self.horizontalLayout_5.addWidget(self.dispensary_2)
        self.emergency_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.emergency_2.setMaximumSize(QtCore.QSize(80, 80))
        self.emergency_2.setStyleSheet("border:none;")
        self.emergency_2.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../MdTouch/Images/ambulance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.emergency_2.setIcon(icon14)
        self.emergency_2.setIconSize(QtCore.QSize(50, 50))
        self.emergency_2.setObjectName("emergency_2")
        self.horizontalLayout_5.addWidget(self.emergency_2)
        superadminBloodBanks.setCentralWidget(self.centralwidget)

        self.retranslateUi(superadminBloodBanks)
        QtCore.QMetaObject.connectSlotsByName(superadminBloodBanks)

    def retranslateUi(self, superadminBloodBanks):
        _translate = QtCore.QCoreApplication.translate
        superadminBloodBanks.setWindowTitle(_translate("superadminBloodBanks", "MainWindow"))
        self.addDoctorLabel.setText(_translate("superadminBloodBanks", "<html><head/><body><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Add</span></p><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Blood Bank</span></p></body></html>"))
        self.broadcastLabel.setText(_translate("superadminBloodBanks", "<html><head/><body><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Broadcast</span></p></body></html>"))
        self.viewBloodBanksLabel.setText(_translate("superadminBloodBanks", "<html><head/><body><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">View</span></p><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Blood Banks</span></p></body></html>"))
        self.title.setText(_translate("superadminBloodBanks", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25pt; font-weight:600; text-decoration: underline;\">MDTouch</span></p></body></html>"))
        self.removeBloodBankLabel.setText(_translate("superadminBloodBanks", "<html><head/><body><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Remove</span></p><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Blood Bank</span></p><p align=\"center\"><br/></p></body></html>"))
        self.analyticsLabel.setText(_translate("superadminBloodBanks", "<html><head/><body><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Analytics</span></p></body></html>"))
        self.fraudLabel.setText(_translate("superadminBloodBanks", "<html><head/><body><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Fraud</span></p><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Inspection</span></p></body></html>"))

