from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from Dialogs.messageBox import *

class removeTestCenter(object):
    def setup(self, removeTestCenter,tcData):
        removeTestCenter.setObjectName("removeTestCenter")
        removeTestCenter.resize(475, 478)
        self.title = QtWidgets.QLabel(removeTestCenter)
        self.title.setGeometry(QtCore.QRect(20, 0, 451, 51))
        self.title.setObjectName("title")
        self.removeButton = QtWidgets.QPushButton(removeTestCenter)
        self.removeButton.setGeometry(QtCore.QRect(170, 420, 131, 41))
        self.removeButton.setObjectName("removeButton")
        self.frame = QtWidgets.QFrame(removeTestCenter)
        self.frame.setGeometry(QtCore.QRect(10, 60, 451, 351))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.nameLabel = QtWidgets.QLabel(self.frame)
        self.nameLabel.setGeometry(QtCore.QRect(25, 40, 81, 41))
        self.nameLabel.setObjectName("nameLabel")
        self.addressLabel = QtWidgets.QLabel(self.frame)
        self.addressLabel.setGeometry(QtCore.QRect(25, 90, 91, 41))
        self.addressLabel.setObjectName("addressLabel")
        self.contactLabel = QtWidgets.QLabel(self.frame)
        self.contactLabel.setGeometry(QtCore.QRect(25, 300, 131, 41))
        self.contactLabel.setObjectName("contactLabel")
        self.stateLabel = QtWidgets.QLabel(self.frame)
        self.stateLabel.setGeometry(QtCore.QRect(25, 210, 61, 41))
        self.stateLabel.setObjectName("stateLabel")
        self.pinCodeLabel = QtWidgets.QLabel(self.frame)
        self.pinCodeLabel.setGeometry(QtCore.QRect(25, 170, 91, 41))
        self.pinCodeLabel.setObjectName("pinCodeLabel")
        self.cityLabel = QtWidgets.QLabel(self.frame)
        self.cityLabel.setGeometry(QtCore.QRect(25, 260, 61, 41))
        self.cityLabel.setObjectName("cityLabel")
        self.name = QtWidgets.QLabel(self.frame)
        self.name.setGeometry(QtCore.QRect(160, 40, 281, 41))
        self.name.setStyleSheet("font-size:12pt;")
        self.name.setObjectName("name")
        self.address = QtWidgets.QLabel(self.frame)
        self.address.setGeometry(QtCore.QRect(160, 90, 281, 71))
        self.address.setStyleSheet("font-size:12pt;")
        self.address.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.address.setObjectName("address")
        self.pinCode = QtWidgets.QLabel(self.frame)
        self.pinCode.setGeometry(QtCore.QRect(160, 170, 181, 41))
        self.pinCode.setStyleSheet("font-size:12pt;")
        self.pinCode.setObjectName("pinCode")
        self.state = QtWidgets.QLabel(self.frame)
        self.state.setGeometry(QtCore.QRect(160, 210, 181, 41))
        self.state.setStyleSheet("font-size:12pt;")
        self.state.setObjectName("state")
        self.city = QtWidgets.QLabel(self.frame)
        self.city.setGeometry(QtCore.QRect(160, 260, 181, 41))
        self.city.setStyleSheet("font-size:12pt;")
        self.city.setObjectName("city")
        self.contactNo = QtWidgets.QLabel(self.frame)
        self.contactNo.setGeometry(QtCore.QRect(160, 305, 181, 31))
        self.contactNo.setStyleSheet("font-size:12pt;")
        self.contactNo.setObjectName("contactNo")
        self.IDLabel = QtWidgets.QLabel(self.frame)
        self.IDLabel.setGeometry(QtCore.QRect(25, 10, 141, 41))
        self.IDLabel.setObjectName("IDLabel")
        self.testCenterID = QtWidgets.QLabel(self.frame)
        self.testCenterID.setGeometry(QtCore.QRect(160, 10, 281, 41))
        self.testCenterID.setStyleSheet("font-size:12pt;\n"
"font-weight:bold;")
        self.testCenterID.setObjectName("testCenterID")

        self.retranslateUi(removeTestCenter,tcData)
        QtCore.QMetaObject.connectSlotsByName(removeTestCenter)

    def retranslateUi(self, removeTestCenter,tcData):
        _translate = QtCore.QCoreApplication.translate
        removeTestCenter.setWindowTitle(_translate("removeTestCenter", " "))
        self.title.setText(_translate("removeTestCenter", "<html><head/><body><p align=\"center\"><span style=\" font-size:15pt; font-weight:600; text-decoration: underline;\">Remove Test Center</span></p></body></html>"))
        self.removeButton.setText(_translate("removeTestCenter", "REMOVE"))
        self.nameLabel.setText(_translate("removeTestCenter", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Name :</span></p></body></html>"))
        self.addressLabel.setText(_translate("removeTestCenter", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Address :</span></p></body></html>"))
        self.contactLabel.setText(_translate("removeTestCenter", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Contact No. :</span></p></body></html>"))
        self.stateLabel.setText(_translate("removeTestCenter", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">State :</span></p></body></html>"))
        self.pinCodeLabel.setText(_translate("removeTestCenter", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Pin Code :</span></p></body></html>"))
        self.cityLabel.setText(_translate("removeTestCenter", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">City :</span></p></body></html>"))
        self.name.setText(_translate("removeTestCenter", "name"))
        self.address.setText(_translate("removeTestCenter", "address"))
        self.pinCode.setText(_translate("removeTestCenter", "pin_code"))
        self.state.setText(_translate("removeTestCenter", "state"))
        self.city.setText(_translate("removeTestCenter", "city"))
        self.contactNo.setText(_translate("removeTestCenter", "contact_no"))
        self.IDLabel.setText(_translate("removeTestCenter", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Test Center ID :</span></p></body></html>"))
        self.testCenterID.setText(_translate("removeTestCenter", "test_center_ID"))

        self.clickEvents(removeTestCenter,tcData)

    def clickEvents(self, parent,tcData):
        self.testCenterID.setText(str(tcData["id"]))
        self.name.setText(str(tcData["name"]))
        self.address.setText(str(tcData["address"]))
        self.pinCode.setText(str(tcData["pin"]))
        self.state.setText(str(tcData["state"]))
        self.city.setText(str(tcData["city"]))
        self.contactNo.setText(str("nil"))
        self.removeButton.clicked.connect(lambda: self.clickOnRemoveButton(parent,tcData))

    def clickOnRemoveButton(self, parent,tcData):
        print(tcData)
        parent.close()
        self.window = messageBox()
        self.window.infoBox("Test Center with ID : " + str(tcData["id"]) + " is deleted.")

        # Deleting TestCenter
        import requests
        URL = "http://127.0.0.1:8000/MDTouch/api/login/" + str(tcData["username"])
        r = requests.delete(url=URL)
        print(r)
